name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      env:
        dest: 's2113517@icho.u.tsukuba.ac.jp:/home/s2113517/www/course/'
      run: |
        echo "${{secrets.SSH_PRIVATE_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -azvur --delete \
          -e 'ssh -p 22 -i ./deploy_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' \
          ./sync_files/* ${{env.dest}}